name: Deploy MkDocs Site

on:
  push:
    branches:
      - main  # Triggers deployment on push to the main branch

env:
  REGISTRY: ghcr.io
  UV_VERSION: 0.9
  PYTHON_VERSION: 3.12
  UV_SYSTEM_PYTHON: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Checkout perovskite plugin for notebooks
        uses: actions/checkout@v4
        with:
          repository: FAIRmat-NFDI/nomad-perovskite-solar-cells-database
          ref: main
          path: ../nomad-perovskite-solar-cells-database

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Prepare Documentation Notebooks
        run: |
          chmod +x scripts/prepare_docs.sh
          ./scripts/prepare_docs.sh

      - name: Build and Deploy
        run: |
          uv run --extra dev mkdocs gh-deploy --force --remote-branch gh-pages